### ISSUE TITLE
EC_FCM_MISMATCH_SENDER_ID

### ISSUE THREAD

**Issue by cristianofromagio** [infobip/mobile-messaging-cordova-plugin#15] opened 2019-04-02 20:55 UTC
Hello, I'm having some issues using the the cordova plugin and the Push Notifications API.

`package.json`
Ionic 4.0 `"@ionic/angular": "4.0.0-rc.0"`
Angular 7.1.4 `"@angular/core": "~7.1.4"`

`config.xml`
```
<plugin name="com-infobip-plugins-mobilemessaging" spec="1.0.14">
    <variable name="ANDROID_FIREBASE_SENDER_ID" value="MY_FIREBASE_SENDER_ID" />
    <variable name="ANDROID_SUPPORT_VER_OVERRIDE" value="false" />
    <variable name="ANDROID_GMS_VER_OVERRIDE" value="false" />
</plugin>
```

`app.component.ts` (there is more code here, I just copied the Infobip plugin related parts)
```typescript
import { Component } from '@angular/core';

declare var window;

import { Platform, AlertController } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {

  public error;

  constructor(
    private platform: Platform,
    private alertCtrl: AlertController,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
  ) {
    this.initializeApp();
  }

  async presentAlert(bodyText) {
    const alert = await this.alertCtrl.create({
      header: 'Nova notificação',
      message: bodyText,
      buttons: ['OK']
    });

    await alert.present();
  };

  initializeApp() {
    this.platform.ready().then(() => {

      if (this.platform.is('mobile') && (this.platform.is('android') || this.platform.is('ios'))) {

        if (window.MobileMessaging) {
          console.log('mobilemessaging');

          window.MobileMessaging.init({
            applicationCode: "MY_INFOBIP_APPLICATION_CODE",
            geofencingEnabled: true,
            android: {
              senderId: "MY_FIREBASE_SENDER_ID"
            },
            ios: {
                notificationTypes: ['alert', 'badge', 'sound']
            }
          },
            function (error) {
              console.log('Init error: ' + error);
              this.error = error;
              // this.presentAlert(error);
            }
          );

          window.MobileMessaging.fetchInstallation(function(installation) {
            console.log('installation');
            console.log(installation);
          });

          window.MobileMessaging.fetchUser(function(user) {
            console.log('user');
            console.log(user);
          });

          window.MobileMessaging.register('messageReceived',
            function (message) {
              console.log('Message Received: ' + message.body);
              // this.presentAlert(message.body);
            }
          );
        }

        this.statusBar.styleDefault();
        this.splashScreen.hide();

      }

    });
  }
}
```

The credentials in Firebase Console matches the variables (`MY_FIREBASE_SENDER_ID` on the code and the FCM Server Key is the same that I put on the Infobip Application configuration.

When I run the app, the user is created in the application since the user counter on the Infobip application panel is updated. But when I try to send a push notification, the app don't receive the push notification and there is a error on the push message relatory.

I use Postman to use the Infobip Push Notifications API:

```
POST push/2/message/single/test HTTP/1.1
Host: MY_INFOBIP_BASE_URL
Authorization: Basic MY_USER_AND_PASSWORD_ENCODED
Accept: application/json

{
    "from": "MY_INFOBIP_APPLICATION_CODE",
    "to": {
        "platform": [
            "Android"
        ]
    },
    "text": "This Message was sent by targeting android platform.",
    "customPayload": {
        "routerLink": "/received"
    }
}
```

This returns the bulkId for the push notification, which I use to get the report:

```
GET push/1/reports?bulkId=API_BULKID_FROM_LAST_STEP HTTP/1.1
Host: MY_INFOBIP_BASE_URL
Authorization: Basic MY_USER_AND_PASSWORD_ENCODED
Accept: application/json
```
And, since I start this debugging adventure, always returns this same error:

```
{
    "results": [
        {
            "bulkId": "API_BULK_ID_FROM_LAST_STEP",
            "messageId": "UNIQUE_MESSAGE_ID",
            "to": "INFOBIP_USER_TOKEN_I_ASSUME",
            "sentAt": "2019-04-02T19:35:34.532+0000",
            "doneAt": "2019-04-02T19:35:34.583+0000",
            "messageCount": 1,
            "price": {
                "pricePerMessage": 0,
                "currency": "UNKNOWN"
            },
            "status": {
                "groupId": 2,
                "groupName": "UNDELIVERABLE",
                "id": 4,
                "name": "UNDELIVERABLE_REJECTED_OPERATOR",
                "description": "Message rejected by operator"
            },
            "error": {
                "groupId": 1,
                "groupName": "HANDSET_ERRORS",
                "id": 8002,
                "name": "EC_FCM_MISMATCH_SENDER_ID",
                "description": "Mismatch FCM Sender ID",
                "permanent": true
            },
            "channel": "PUSH",
            "callbackData": "{\"externalPersonId\":\"\",\"msisdn\":\"\"}"
        }
    ]
}
```

Is there some misconfiguration? Am I missing something here?

**Comment by tjuric** [comment] 2019-04-03 16:57
Hi @cristianofromagio,

By checking the provided code, I don't see any issues, except that in `init` method senderId doesn't need to be provided (anymore) -  required setup can be checked in 3rd bullet of quick start guide https://github.com/infobip/mobile-messaging-cordova-plugin/blob/master/README.md.

I can confirm that you used proper Infobip application code while targeting push destinations. However, I cannot confirm that your Firebase sender ID provided in Cordova project and server key provided on our web portal match, but since you stated that they match, I can try to pinpoint on one thing that you might also check on your side.

Are you maybe using google-services.json file in your project (Google services plugin)?

**Comment by cristianofromagio** [comment] 2019-04-03 18:19
Hello @tjuric, thanks for the follow up!

No, right now I'm not using the `google-services.json` anywhere in my project.

Here is my full `config.xml`

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="br.com.cristianofromagio.sandbox" version="1.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name short="Cristiano Sandbox">CristianoSandbox</name>
    <description>Sandbox App.</description>
    <author email="email@email.com.br" href="https://www.example.com.br">Example</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="SplashScreenSpinnerColor" value="#1f3d7b" />
    <platform name="android">
        <allow-intent href="market:*" />
        <!-- android icons -->
        <!-- splash android -->
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <!-- iOS icons -->
        <!-- splash iOS -->
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-sqlite-storage" spec="2.6.0" />
    <plugin name="cordova-plugin-fullscreen" spec="1.2.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="3.0.0" />
    <plugin name="cordova-plugin-geolocation" spec="4.0.1" />
    <plugin name="cordova-plugin-native-spinner" spec="1.1.3" />
    <plugin name="cordova-plugin-market" spec="1.2.0" />
    <plugin name="cordova-plugin-screen-orientation" spec="3.0.1" />
    <plugin name="cordova-android-support-gradle-release" spec="2.0.1">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <preference name="cordova.plugins.diagnostic.modules" value="LOCATION" />
    <plugin name="cordova.plugins.diagnostic" spec="4.0.12">
        <variable name="ANDROID_SUPPORT_VERSION" value="28.+" />
    </plugin>
    <plugin name="com-infobip-plugins-mobilemessaging" spec="1.0.14">
        <variable name="ANDROID_FIREBASE_SENDER_ID" value="FIREBASE_SENDER_ID" />
        <variable name="ANDROID_SUPPORT_VER_OVERRIDE" value="false" />
        <variable name="ANDROID_GMS_VER_OVERRIDE" value="false" />
    </plugin>
    <engine name="browser" spec="5.0.4" />
    <engine name="android" spec="7.1.4" />
</widget>
```

**Comment by tjuric** [comment] 2019-04-04 13:36
@cristianofromagio, can you contact us over our support e-mail? 

Mention this GitHub issue and try following: 
1. create app (with you API key generated for Firebase project)
2. start your app with current implementation (use sender ID from the same Firebase project)
3. try to send notification to that device over our customer portal or API
4. send us app code and push reg ID (since it's sensitive data) to support@infobip.com e-mail so we can continue the discussion there.

**Comment by tjuric** [comment] 2019-05-07 13:59
Hi @cristianofromagio, are there any updates?

**Comment by tjuric** [comment] 2019-05-15 09:03
@cristianofromagio, have you contacted us over our support e-mail? We'll close this issue here since there's sensitive data which needs to be provided. It will be reopened if needed. 

You might add your comments here.

**Closed by tjuric** 2019-05-15 09:03 UTC
