### ISSUE TITLE
not exec event messageReceived when clic notification icon

### ISSUE THREAD

**Issue by rgfpy** [infobip/mobile-messaging-cordova-plugin#2] opened 2017-05-09 22:32 UTC
When the notification arrives and one clicks on the notification opens the APP but when the messageReceived event is no longer running, the message received in the notification is displayed again it only shows the notification if the APP is open.

**Comment by stanislavin** [comment] 2017-05-10 07:40
Hi @rgfpy,

Please provide more details about your platform (is it iOS or Android) and which version of plugin you use.

Also do I understand correctly that your issue is that notification is only shown if the app is open?

**Comment by rgfpy** [comment] 2017-05-10 12:36
Hi,
The platform is Android and tested in version 7 and 6.

Yes it is only if the APP is open the event "messageReceived" is executed, but the notifications arrive correctly in notification area.

**Comment by stanislavin** [comment] 2017-05-10 12:48
To narrow down the issue, please confirm:

If the app is not running, you can see notifications in the notification area. But "messageReceived" event is not delivered to the app if the app is being opened afterwards.

**Comment by rgfpy** [comment] 2017-05-10 12:59
Yes the notification arrived correctly, but when opening the application from the notification area the event "messageReceived" is not ejecuted

**Comment by stanislavin** [comment] 2017-05-11 12:53
@rgfpy thanks for reporting, we were able to track down this issue. We will post an update here when the issue will be resolved.

**Comment by nestordavalos** [comment] 2017-05-18 22:06
Good afternoon, do we have any news about the case?

best regards

**Comment by stanislavin** [comment] 2017-05-19 05:22
@nestordavalos we are actively working on the fix now to close the issue with next release of the plugin.

**Comment by stanislavin** [comment] 2017-05-23 16:24
The issue is fixed with 0.2.2 release.

**Closed** 2017-05-23 16:24 UTC
