### ISSUE TITLE
Migrating to Xcode 10.2.1

### ISSUE THREAD

**Issue by rstylesoftlab** [infobip/mobile-messaging-cordova-plugin#16] opened 2019-04-24 13:42 UTC
Hello.
I'm trying to migrate to Xcode 10.2.1 from 10.1. And when building my app in Xcode i got such error:
![Снимок экрана 2019-04-24 в 16 36 28](https://user-images.githubusercontent.com/35531263/56663900-c613b100-66af-11e9-939a-0f990876f444.png)

I use plugin version 1.0.14.
Can you advise me something please?

**Comment by kas-kad** [comment] 2019-04-24 16:06
Hello, at this moment we don't support Swift 5, however we plan to implement it **in a week or so**. I only can advise you to update your current version of plugin to 1.0.15 as it contains a few useful improvements.

**Comment by kas-kad** [comment] 2019-04-24 16:09
As a workaround, you can switch your project explicitly to Swift 4.2: 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/1947169/56675327-82777200-66c4-11e9-8854-4ca1df935ca9.png">

**Comment by rstylesoftlab** [comment] 2019-04-25 07:06
Thank you for answer.
I've already switched my project to Swift 4.2, but error still exists.
![Снимок экрана 2019-04-25 в 9 59 13](https://user-images.githubusercontent.com/35531263/56715721-243ca480-6741-11e9-852d-c43365d900a4.png)

I guess i should wait for new version of plugin with support of Swift 5 that you plan to implement. I will wait for it very much.

**Comment by kas-kad** [comment] 2019-04-25 08:36
Could you please provide the output of the command: `xcodebuild -version`

**Comment by kas-kad** [comment] 2019-04-25 08:37
Also, to make project work, try to clean project `cmd + shift + k` and build folder `cmd + option + shift + k`

**Comment by rstylesoftlab** [comment] 2019-04-25 11:56
```
xcodebuild -version
Xcode 10.2.1
Build version 10E1001
```

I have cleaned project as you described. Error still the same.

**Comment by kas-kad** [comment] 2019-04-25 15:38
Did you try to remove out plugin and install it again with version 1.0.15?

**Comment by kas-kad** [comment] 2019-04-25 15:56
1.0.15 has changes related to the iOS dynamic framework building. I could not reproduce your issue on my machine with plugin of version 1.0.15.

**Comment by solinder** [comment] 2019-04-26 08:55
Thank you! 1.0.15 is building correctly.

I have some question about settings of cordova-plugin-add-swift-support. By default, it adds the Swift 4 support. Is it nesessary to add setting to support Swift 4.2 to provide the correct work of your plugin? 
`<preference name="UseSwiftLanguageVersion" value="4.2" />`
Or it isn't nesessary?
Now i have not add this setting and the app is building normally. But i'm not sure that it is right.

**Comment by kas-kad** [comment] 2019-04-26 08:59
Hello @solinder thanks for the feedback. Your question will remain unanswered because we didn't start the migration to Swift 5 yet. If the solution that you have right now works for you, then stick to it.

**Comment by rstylesoftlab** [comment] 2019-04-26 09:05
Excuse me, i accidentally wrote from another account (solinder). 
So using 1.0.15 solved my problem. Thank you for your help!

**Comment by kas-kad** [comment] 2019-05-24 14:11
Ok, closing the issue.

**Closed by kas-kad** 2019-05-24 14:11 UTC
